version: '3.8'

services:
  app:
    build: .
    ports:
      - "8108:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Israel@2026
      MYSQL_DATABASE: istam_paiement
      MYSQL_USER: IZOU
      MYSQL_PASSWORD: Izou@2026
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: